- GitReleaseManager.yaml
> (GH-6) modified GitReleaseManager.yaml

- src/Cake.ESLint.Tests/Cake.ESLint.Tests.csproj
- src/Cake.ESLint/Cake.ESLint.csproj
- src/Directory.Build.targets
> (GH-7) enabled deterministic builds

- README.md
> (GH-9) added a link to GitHub discussions in README

- demo/frosting/.gitignore
- demo/frosting/build.ps1
- demo/frosting/build.sh
- demo/frosting/build/Build.csproj
- demo/frosting/build/Program.cs
- demo/frosting/src1/.eslintrc.json
- demo/frosting/src1/my-test-file.js
- demo/frosting/src2/.eslintrc.json
- demo/frosting/src2/my-test-file.js
- demo/frosting/src2/package.json
- demo/script/build.cake
> (GH-14) added a demo for Frosting

- demo/frosting/build/Program.cs
- demo/script/build.cake
- recipe.cake
- src/Cake.ESLint.Tests/ESLintAliasesTests.Runs_tool_with_given_action.verified.txt
- src/Cake.ESLint.Tests/ESLintRunnerTests.cs
- src/Cake.ESLint.Tests/Fixtures/ESLintAliasesFixture.cs
- src/Cake.ESLint/ESLintAliases.cs
- src/Cake.ESLint/ESLintRunner.cs
- src/Cake.ESLint/ESLintSettings.cs
- src/Cake.ESLint/ESLintSettingsExtensions.cs
- src/Cake.ESLint/Extensions/EnumerableExtensions.cs
- src/Cake.ESLint/Namespaces.cs
```
--config path::String
--env [String]
--ext [String]
--global [String]
--parser String
--parser-options Object
--resolve-plugins-relative-to path::String
```
fixes #18
> (GH-18) added basic configuration options

- src/Cake.ESLint.Tests/ESLintRunnerTests.cs
- src/Cake.ESLint/ESLintRunner.cs
- src/Cake.ESLint/ESLintSettings.cs
- src/Cake.ESLint/ESLintSettingsExtensions.cs
and plugins.
--rulesdir [path::String]
--plugin [String]
--rule Object
fixes #19
> (GH-19) added options for specifying rules

- src/Cake.ESLint.Tests/ESLintAliasesTests.Runs_tool_with_given_action.verified.txt
- src/Cake.ESLint.Tests/ESLintAliasesTests.cs
- src/Cake.ESLint.Tests/ESLintRunnerTests.cs
- src/Cake.ESLint/ESLintFixType.cs
- src/Cake.ESLint/ESLintRunner.cs
- src/Cake.ESLint/ESLintSettings.cs
- src/Cake.ESLint/ESLintSettingsExtensions.cs
--fix
--fix-dry-run
--fix-type
> (GH-20) added options for fixing problems

- src/Cake.ESLint.Tests/ESLintRunnerTests.cs
- src/Cake.ESLint.sln.DotSettings
- src/Cake.ESLint/ESLintRunner.cs
- src/Cake.ESLint/ESLintSettings.cs
- src/Cake.ESLint/ESLintSettingsExtensions.cs
--ignore-path
--no-ignore
--ignore-pattern
fixes #21
> (GH-21) added options for ignoring files

- src/Cake.ESLint.Tests/ESLintRunnerTests.cs
- src/Cake.ESLint/ESLintRunner.cs
- src/Cake.ESLint/ESLintSettings.cs
--quiet
--max-warnings
fixes #22
> (GH-22) added options for handling warnings

- src/Cake.ESLint.Tests/ESLintRunnerTests.cs
- src/Cake.ESLint/ESLintRunner.cs
- src/Cake.ESLint/ESLintSettings.cs
--no-inline-config
--report-unused-disable-directives
fixes #23
> (GH-23) added options for inline configuration comments

- src/Cake.ESLint.Tests/ESLintRunnerTests.cs
- src/Cake.ESLint/ESLintCacheStrategy.cs
- src/Cake.ESLint/ESLintRunner.cs
- src/Cake.ESLint/ESLintSettings.cs
--cache
--cache-location
--cache-strategy
fixes #24
> (GH-24) added options for caching

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- demo/frosting/build/Build.csproj
- demo/script/.config/dotnet-tools.json
- demo/script/build.cake
- src/Cake.ESLint.Tests/Cake.ESLint.Tests.csproj
- src/Cake.ESLint/Cake.ESLint.csproj
and CakeContrib.Guidelines to 1.3.0
fixes #123
> (#123) bumped Cake to 2.0.0

- .github/renovate.json
This should allow renovate to auto-merge PRs about GitHub Actions
> (maint) switch renovate to the testing preset

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- global.json
- src/Cake.ESLint.Tests/Cake.ESLint.Tests.csproj
- src/Cake.ESLint/Cake.ESLint.csproj
> Updated Cake.Core reference to Cake 3.0.0

- src/Cake.ESLint/ESLintCacheStrategy.cs
Fixes XML comments for `ESLintCacheStrategy`
Fixes #280
> Fix comments

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/publishDocs.yml
> (#321) Buped GitHub Runners

- demo/frosting/build/Build.csproj
- demo/script/.config/dotnet-tools.json
- demo/script/build.cake
- src/Cake.ESLint.Tests/Cake.ESLint.Tests.csproj
- src/Cake.ESLint/Cake.ESLint.csproj
and CakeContrib.Guidelines to 1.5.1
fixes #396
> (#396) Update Cake.Core to 4.0.0

- recipe.cake
> (#463) disable CodeCov

- .github/renovate.json
> (#541) updated renovate config

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- demo/frosting/build.sh
- demo/frosting/build/Build.csproj
- demo/script/.config/dotnet-tools.json
- demo/script/build.cake
- demo/script/build.sh
- global.json
- recipe.cake
- src/Cake.ESLint.Tests/Cake.ESLint.Tests.csproj
- src/Cake.ESLint/Cake.ESLint.csproj
> (#545) Bump Cake to 5.0.0
